# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli
#https://gill.net.in/posts/auth-microservice-rust-actix-web1.0-diesel-complete-tutorial/
#tutorial
[print_schema]
file = "src/schema.rs"

[migrations_directory]
dir = "migrations"
